micronaut:
  application:
    name: micronaut-kotlin

datasources:
  default:
    #url: jdbc:h2:mem:devDb
    url: jdbc:h2:./data/sample
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
jpa:
  default:
    packages-to-scan:
      'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: none


flyway:
  datasources:
    default:
      enabled: true
    baseline-on-migrate: true
#  url: jdbc:h2:./data/sample
#  username: sa
#  password: ''

endpoints:
  flyway:
    enabled: true
    sensitive: false