micronaut:
  application:
    name: demo

datasources:
  default:
    #url: jdbc:h2:mem:devDb
    url: jdbc:h2:file:./data/sample
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
